### ISSUE TITLE
1

### ISSUE THREAD

**Issue by forever-young-hh** [weijiaooaa/MentalHealth#4]

**Comment by forever-young-hh** [comment]
你好，你这个心理咨询系统，我可以借来改改数据吗？

**Comment by forever-young-hh** [comment]
我想借用你这个系统来做课程项目，但是目前遇到一个问题就是心理测评那一块的样式加载不出来，然后访问里面的地址也被限制了，请问您知道怎么解决吗？可以指导一下我吗，谢谢啦。如果不方便也没事，我自己想想办法。打扰你了

**Comment by weijiaooaa** [comment]
> 我想借用你这个系统来做课程项目，但是目前遇到一个问题就是心理测评那一块的样式加载不出来，然后访问里面的地址也被限制了，请问您知道怎么解决吗？可以指导一下我吗，谢谢啦。如果不方便也没事，我自己想想办法。打扰你了

我记得那里当时是直接在百度了一个测评网址贴上去的，被限制了可能就是那个网址被封了，你可以重新去百度下其他测评网站，然后把那块的逻辑换一下就行

**Comment by forever-young-hh** [comment]
我没找到那个测评网址，但是那个加载的Css样式的网址出错了
就是这个网址，是不是就是这个问题啊？
http://serrinawss.java.jspee.cn:80/css/in3.css

**Comment by forever-young-hh** [comment]
在那个/study/psychologicalTest.html页面那里

**Comment by weijiaooaa** [comment]
> 我没找到那个测评网址，但是那个加载的Css样式的网址出错了 就是这个网址，是不是就是这个问题啊？ http://serrinawss.java.jspee.cn:80/css/in3.css

看了一下，那应该就是我贴的那个网站封了，我当时是直接百度的，然后F12直接把源码cp到项目里面的，相当于是复刻了一版，所以那个网站要是凉了，那我这个肯定也运行不起来，所以建议你要不就自己写个简易版的HTML页面(比如从题库中挑些题，按分数段给用户跳转不同的测试结果页面，这块你可以看下逻辑应该不太难写，前端都有模板可以套用)，要不也就百度下那种比较简单的测试网站，cp下他们的代码也行

**Comment by forever-young-hh** [comment]
好，谢谢你，真的谢谢了。我还以为是我改项目改出问题了。

**Comment by forever-young-hh** [comment]
你好，我刚刚发现他那个网站恢复了，数据都加载出来了，但是我不太敢用了，怕到时候答辩突然又进不去

**Comment by weijiaooaa** [comment]
> 你好，我刚刚发现他那个网站恢复了，数据都加载出来了，但是我不太敢用了，怕到时候答辩突然又进不去

hhhhhh，那你看能不能把这个css复制到本地，然后替换掉代码里引用的这个css，如果不行的话，那你就还是按我上面说的去做，自己写个简易版的HTML，保险一点儿。。。

**Comment by forever-young-hh** [comment]
感觉还是写个简单点的保险一些，谢谢啦
